  name: kj.mj.plugin.player_warp_item.PlayerWarpItem
  main: PlayerWarpItem
  version: 1.0.0
  api-version: 1.20
  description: 아이템 우클릭 시 워프

  commands:
    워프아이템:
      permission: op

depend:
  - HQFramework